// This is a Declarative Pipeline, written in Groovy syntax

pipeline {
    // Here, we tell Jenkins to find any available agent with the 'linux' label
    agent {
        label 'Linux-uzaif-agent1'
    }

    stages {
        // A stage is a logical block in our pipeline, like 'Build' or 'Test'
        stage('Install Dependencies') {
            steps {
                // 'sh' executes a shell command on the agent
                dir('jenkins-aws-demo') {
                    sh 'npm install'
                }
            }
        }
        stage('Run Tests') {
            steps {
                dir('jenkins-aws-demo'){

                    sh 'npm test'
                }
            }
        }
    }
}
